### PR TITLE
Adding Maven module

### PR DESCRIPTION
**Pull request by gandhiuw**
This is a pull request. What I have done it taken your code repository, made a copy for myself, made changes to this copy and via this pull request I'm asking you to either accept or reject these changes.
If you choose to "Merge", that means you think are changes are acceptable and you are ready to incorporate my changes into the original copy

### CODE REVIEW

**Comment by gandhiuw** [comment]
Once you "merge" this pull request, we can talk about what are the file I've checked in and why.

**Comment by gandhiuw** [comment]
@nehabindle Here is a create article about what is a version control system and why  it's useful.
https://www.howtogeek.com/180167/htg-explains-what-is-github-and-what-do-geeks-use-it-for/

**Comment by nehabindle** [comment]
Hey
Thanks for sharing.

**Comment by gandhiuw** [comment]
I haven't  shared this. It needs to be merged. Read comments on the pull
request

**Comment by nehabindle** [comment]
Ok.. I just Saw the mail but didn’t read it. Will read it now

**Review by nehabindle — APPROVED** [review]
Merging

**Pull request merged**
